### ISSUE TITLE
[BUG]: Workflow cannot be parsed

### ISSUE THREAD

**Issue by tsschaffert** [woodruffw/github-actions-models#12]
### Pre-submission checks

- [X] I am **not** filing a feature request. These should be filed via the feature request form instead.
- [X] I have looked through the [open issues](https://github.com/woodruffw/zizmor/issues?q=is%3Aissue+is%3Aopen+) for a duplicate report.

### Expected behavior

I expected `zizmor <path to repo>` to successfully analyze the repository.

### Actual behavior

The command fails with the following error:
```
Error: invalid GitHub Actions workflow: "<path to repo>/.github/workflows/test.yaml"

Caused by:
    data did not match any variant of untagged enum Trigger
```

### Reproduction steps

Using the following test.yaml workflow causes the issue:
```
# This causes the error
on:
  repository_dispatch:
    types: nautinfo-docker-image-digest-changed
```

This can be fixed by using the following syntax instead:
```
# This works
on:
  repository_dispatch:
    types:
    - nautinfo-docker-image-digest-changed
```

Both seem to be valid Github Action Workflow Syntax.
